### ISSUE TITLE
ValueError: bytes must be in range(0, 256)

### ISSUE THREAD

**Issue by jsarkisian** [fox-it/BloodHound.py#71] opened 2021-07-20 15:01 UTC
When running the following I get a large error blob after it successfully connects to the LDAP server and states how many computers it has found.

**Command run:**

`python3 bloodhound.py -u USER -p 'PASS' -c All,LoggedOn -d DOMAIN.com`

**Error output (redacted):**

```
INFO: Found AD domain: DOMAIN.com
INFO: Connecting to LDAP server: DC.DOMAIN.com
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found NUMBERS computers
INFO: Connecting to LDAP server: DC.DOMAIN.com
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/tools/BloodHound.py/bloodhound/ad/utils.py", line 345, in resolve_aces
    entry = self.addomain.sidcache.get(ace['sid'])
  File "/root/tools/BloodHound.py/bloodhound/ad/utils.py", line 438, in get
    return self._cache[entry]
KeyError: 'S-1-5-21-NUMBERS-2617'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/pool.py", line 592, in _handle_results
    cache[job]._set(i, obj)
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/multiprocessing/pool.py", line 776, in _set
    self._callback(self._value)
  File "/root/tools/BloodHound.py/bloodhound/enumeration/memberships.py", line 408, in process_acldata
    data['Aces'] += self.aceresolver.resolve_aces(aces)
  File "/root/tools/BloodHound.py/bloodhound/ad/utils.py", line 350, in resolve_aces
    ldapentry = self.resolver.resolve_sid(ace['sid'], use_gc)
  File "/root/tools/BloodHound.py/bloodhound/enumeration/objectresolver.py", line 132, in resolve_sid
    for entry in entries:
  File "/root/tools/BloodHound.py/bloodhound/ad/domain.py", line 156, in search
    for e in sresult:
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/site-packages/ldap3/extend/standard/PagedSearch.py", line 56, in paged_search_generator
    result = connection.search(search_base,
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/site-packages/ldap3/core/connection.py", line 838, in search
    request = search_operation(search_base,
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/site-packages/ldap3/operation/search.py", line 371, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/site-packages/ldap3/operation/search.py", line 290, in compile_filter
    matching_filter['assertionValue'] = AssertionValue(prepare_filter_for_sending(filter_node.assertion['value']))
  File "/root/.pyenv/versions/3.8.7/lib/python3.8/site-packages/ldap3/protocol/convert.py", line 205, in prepare_filter_for_sending
    return bytes(ints)
ValueError: bytes must be in range(0, 256)
```

This is a new one, never seen it. If I do NOT specify that I want to collect ```All,LoggedOn``` then it runs as expected

Thanks!

**Comment by dirkjanm** [comment] 2021-07-22 11:36
Which version of ldap3 is this? And could you try either upgrading or downgrading it to see if the problem keeps occurring? Pretty sure this is an issue with the ldap3 library but not sure what the root cause is.

**Comment by L1NKD34D** [comment] 2021-08-05 20:56
```
Traceback (most recent call last):
  File "bloodhound.py", line 5, in <module>
    bloodhound.main()
  File "/opt/impacket/BloodHound.py/bloodhound/__init__.py", line 300, in main
    timestamp=timestamp)
  File "/opt/impacket/BloodHound.py/bloodhound/__init__.py", line 76, in run
    membership_enum.enumerate_memberships(timestamp=timestamp)
  File "/opt/impacket/BloodHound.py/bloodhound/enumeration/memberships.py", line 488, in enumerate_memberships
    self.enumerate_users(timestamp)
  File "/opt/impacket/BloodHound.py/bloodhound/enumeration/memberships.py", line 200, in enumerate_users
    user['HasSIDHistory'].append(self.aceresolver.resolve_sid(historysid))
  File "/opt/impacket/BloodHound.py/bloodhound/ad/utils.py", line 382, in resolve_sid
    ldapentry = self.resolver.resolve_sid(sid, use_gc)
  File "/opt/impacket/BloodHound.py/bloodhound/enumeration/objectresolver.py", line 132, in resolve_sid
    for entry in entries:
  File "/opt/impacket/BloodHound.py/bloodhound/ad/domain.py", line 156, in search
    for e in sresult:
  File "/usr/local/lib/python3.6/dist-packages/ldap3/extend/standard/PagedSearch.py", line 68, in paged_search_generator
    None if cookie is True else cookie)
  File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 850, in search
    check_names=self.check_names)
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 371, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 290, in compile_filter
    matching_filter['assertionValue'] = AssertionValue(prepare_filter_for_sending(filter_node.assertion['value']))
  File "/usr/local/lib/python3.6/dist-packages/ldap3/protocol/convert.py", line 205, in prepare_filter_for_sending
    return bytes(ints)
ValueError: bytes must be in range(0, 256)
```

Received a similar error when using 2.9.X. Successfully worked around the issue downgrading to 2.8 as 
```
python3 -m pip uninstall ldap3
python3 -m pip install ldap3==2.8
```

**Comment by dirkjanm** [comment] 2022-02-15 10:00
Closing since this is an issue in the upstream ldap3 library, and isn't present in the latest version

**Closed by dirkjanm** 2022-02-15 10:00 UTC
