### ISSUE TITLE
collecting sessions for a longer time

### ISSUE THREAD

**Issue by s0i37** [fox-it/BloodHound.py#78] opened 2021-12-01 17:36 UTC
Hello.
`Bloodhound.py` collect sessions quick. Instead, it is more efficient to collect sessions for a longer time, but also only from specified targets (DC).
```
netview.py corp/user -target dc01.corp.local > sessions.txt
netview.py corp/user -target dc02.corp.local >> sessions.txt
netview.py corp/user -target dc03.corp.local >> sessions.txt
```
After a few hours I collect thousand sessions. But `bloodhound.py` collects far less.
I implemented import `netview.py` results to computers.json, but it seems to me a bit ugly.
May be it need to implement some addition option for `bloodhound.py` for long time collecting sessions only for specified hosts?

**Comment by dirkjanm** [comment] 2022-02-15 09:59
Duplicate of #22, closing

**Closed by dirkjanm** 2022-02-15 09:59 UTC
