### ISSUE TITLE
several compilations give stacktraces. 

### ISSUE THREAD

**Issue by No-0Peration** [fox-it/BloodHound.py#34] opened 2020-02-12 13:15 UTC
Bloodhound-python: traces on a Rasperry Pi 3 1Gb mem running Kali GNU/Linux Rolling \n \l

On default collections only LocalAdmin and Session are working other collections from default give
stack traces.

DEBUG: Authentication: username/password
DEBUG: Resolved collection methods: localadmin, session, group, trusts
DEBUG: Using DNS to retrieve domain information
DEBUG: Querying domain controller information from DNS
DEBUG: Using domain hint:
INFO: Found AD domain: 
DEBUG: Found primary DC: 
DEBUG: Found Global Catalog server: 
DEBUG: Found Global Catalog server: 
DEBUG: Found Global Catalog server: 
DEBUG: Found Global Catalog server: 
DEBUG: Using LDAP server: 
DEBUG: Using base DN: 
INFO: Connecting to LDAP server: 
DEBUG: Authenticating to LDAP server
INFO: Found 1 domains
INFO: Found 1 domains in the forest
INFO: Found 1577 computers
DEBUG: Writing users to file: users.json
Traceback (most recent call last):
  File "/home/user/.local/bin/bloodhound-python", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 286, in main
    disable_pooling=args.disable_pooling)
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 75, in run
    membership_enum.enumerate_memberships()
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/enumeration/memberships.py", line 486, in enumerate_memberships
    self.enumerate_users()
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/enumeration/memberships.py", line 204, in enumerate_users
    self.parse_gmsa(user, entry)
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/enumeration/memberships.py", line 392, in parse_gmsa
    _, aces = parse_binary_acl(user, 'user', ADUtils.get_entry_property(entry, 'msDS-GroupMSAMembership', raw=True), self.addc.objecttype_guid_map)
AttributeError: 'ADDC' object has no attribute ‘objecttype_guid_map’

Other not default collection errors:

For example ACL or DCOnly give stack traces.

Traceback (most recent call last):
  File "/home/user/.local/bin/bloodhound-python", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 286, in main
    disable_pooling=args.disable_pooling)
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 72, in run
    self.pdc.prefetch_info('objectprops' in collect, 'acl' in collect)
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/ad/domain.py", line 385, in prefetch_info
    self.get_computers(include_properties=props, acl=acls)
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/ad/domain.py", line 352, in get_computers
    for entry in entries:
  File "/home/user/.local/lib/python2.7/site-packages/bloodhound/ad/domain.py", line 150, in search
    for e in sresult:
  File "/home/user/.local/lib/python2.7/site-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
    None if cookie is True else cookie)
  File "/home/user/.local/lib/python2.7/site-packages/ldap3/core/connection.py", line 765, in search
    raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type ms-mcs-admpwdexpirationtime

Also the computers.json is  not parsed by bloodhound 3.0 on macOS Catalina 10.15.3 and Neo4j 3.5.14
dev-console error:

Uncaught (in promise) TypeError: Cannot read property 'flatMap' of undefined
    at ov (bundle.js:116)
    at a (bundle.js:116)
    at Object.Xy [as computers] (bundle.js:116)
    at bundle.js:116
    at c (bundle.js:27)
    at Generator._invoke (bundle.js:27)
    at Generator.E.forEach.e.<computed> [as next] (bundle.js:27)
    at gv (bundle.js:116)
    at a (bundle.js:116)
    at bundle.js:116
    at new Promise (<anonymous>)
    at t.<anonymous> (bundle.js:116)
    at t.<anonymous> (bundle.js:116)
    at t.<anonymous> (bundle.js:116)
    at c (bundle.js:27)
    at Generator._invoke (bundle.js:27)

**Comment by No-0Peration** [comment] 2020-02-13 06:19
So since there is no LAPS and GSMA in the Active directory schema i'm testing against. this probably craps out.

**Comment by dirkjanm** [comment] 2020-02-13 20:06
Thanks for the report. I've pushed some fixes to master which should address these issues. I don't know if you're still in a position to test, but it would be cool if you could.

**Comment by justin-p** [comment] 2020-02-13 21:02
Ran into the same issues today. The original errors posted by No-0Peration are fixed, though there is still a error on a LAPS attribute, `ms-mcs-admpwd`.

```
loodhound-python -u USER -p PASS -dc lab-dc01.lab.justin-p.me -gc lab-dc01.lab.justin-p.me -d lab.justin-p.me -ns 10.11.12.1 -c all
[...SNIP...]
INFO: Querying computer: LAB-DC01.lab.justin-p.me
ERROR: Unhandled exception in computer LAB-DC01.lab.justin-p.me processing: 'ms-mcs-admpwd'
INFO: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/computers.py", line 235, in process_computer
    results_q.put(('computer', c.get_bloodhound_data(entry, self.collect)))
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/ad/computer.py", line 151, in get_bloodhound_data
    self.addc.objecttype_guid_map)
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/acls.py", line 138, in parse_binary_acl
    ace_object.acedata.get_object_type().lower() == objecttype_guid_map['ms-mcs-admpwd'] and \
KeyError: 'ms-mcs-admpwd'

WARNING: Could not resolve SID: S-1-5-21-4293559167-2054256270-1955830364-1131
WARNING: Could not resolve SID: S-1-5-21-4293559167-2054256270-1955830364-1132
ERROR: Unhandled exception in computer LAB-PC02.lab.justin-p.me processing: 'ms-mcs-admpwd'
INFO: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/computers.py", line 247, in process_computer
    results_q.put(('computer', c.get_bloodhound_data(entry, self.collect)))
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/ad/computer.py", line 151, in get_bloodhound_data
    self.addc.objecttype_guid_map)
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/acls.py", line 138, in parse_binary_acl
    ace_object.acedata.get_object_type().lower() == objecttype_guid_map['ms-mcs-admpwd'] and \
KeyError: 'ms-mcs-admpwd'

WARNING: Could not resolve SID: S-1-5-21-4293559167-2054256270-1955830364-1133
ERROR: Unhandled exception in computer LAB-PC01.lab.justin-p.me processing: 'ms-mcs-admpwd'
INFO: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/computers.py", line 247, in process_computer
    results_q.put(('computer', c.get_bloodhound_data(entry, self.collect)))
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/ad/computer.py", line 151, in get_bloodhound_data
    self.addc.objecttype_guid_map)
  File "/usr/local/lib/python3.7/dist-packages/bloodhound-1.0.0-py3.7.egg/bloodhound/enumeration/acls.py", line 138, in parse_binary_acl
    ace_object.acedata.get_object_type().lower() == objecttype_guid_map['ms-mcs-admpwd'] and \
KeyError: 'ms-mcs-admpwd'

INFO: Done in 00M 02S

**Comment by justin-p** [comment] 2020-02-13 21:17
https://github.com/fox-it/BloodHound.py/pull/35 should fix the issue.

**Comment by No-0Peration** [comment] 2020-02-14 11:01
Thanx monday i will be able to test it!

**Comment by No-0Peration** [comment] 2020-02-17 13:09
Tested and all ingestor problems look solved for ancient schema. still importing computers.json in bloodhound3.0 gives a flatmap error. All other .jsons do not. 

![image](https://user-images.githubusercontent.com/14880031/74656770-1c963280-518f-11ea-975c-50673d3d5dbf.png)

**Comment by dirkjanm** [comment] 2020-02-17 13:39
Glad to hear the ingestor problems are solved. I can't really debug the import error without having access to your JSON file as the stack trace doesn't really tell me much (since it's from minified javascript).

**Comment by No-0Peration** [comment] 2020-02-18 06:29
Sadly i cant share it because there is no way i can anonimize it. Any way to troubleshoot it my self besides the developer view in Bloodhound?

**Comment by dirkjanm** [comment] 2020-02-18 07:37
You could run the bloodhound UI from source instead of using the prebuilt version, that might give a more detailed stack trace. Also are you 100% sure the problem is in your computers.json?

**Comment by No-0Peration** [comment] 2020-02-18 08:02
Sure will try that. All other JSON's import without error

**Comment by No-0Peration** [comment] 2020-02-18 08:22
running from source doesnt change it. the json file validates.

**Comment by Incisive** [comment] 2020-02-20 14:51
Having this exact same issue, failing on importing computers.json which in our environment is 3.4 MB

**Comment by dirkjanm** [comment] 2020-02-20 20:59
If you could also do the collection with sharphound and compare the results maybe I could find the root cause.

**Comment by dirkjanm** [comment] 2020-02-21 20:24
I just was able to pinpoint the issue and it should be fixed with the latest commit in master. Can someone test this to confirm?

**Closed** 2020-02-21 20:23 UTC
Labels: bug
